name: Deploy to GKE

on:
  push:
    branches:
      - main     # Trigger only when development branch is merged into main

env:
  PROJECT_ID: firm-pentameter-475405-i2
  GKE_CLUSTER: hello-world-cluster
  GKE_ZONE: asia-south1-a
  GAR_LOCATION: asia-south1
  REPOSITORY: hello-worldapprepo
  IMAGE: hello_world_app

jobs:
  build-and-deploy:
    runs-on: ubuntu-22-04

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Authenticate with GCP using Service Account
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Set up gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # 4️⃣ Configure Docker to use Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      # 5️⃣ Install app dependencies (Node.js)
      - name: Install Node.js dependencies
        run: |
          npm install
          # optional: npm run build

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .

      # 7️⃣ Push image to Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

      # 8️⃣ Get GKE credentials
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }} --project ${{ env.PROJECT_ID }}

      # 9️⃣ Update image in Kubernetes manifests
      - name: Update Kubernetes Deployment image
        run: |
          sed -i "s|image:.*|image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}|g" k8s/deployment.yaml

      # 🔟 Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/hello-world-deployment
